default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt
        args:
          - --indent
          - '4'
          - --case-indent
          - --simplify
          - --write
        exclude: '\.bashrc'
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words=.codespellignore
          - --quiet-level=2
          # - --write-changes
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
  - repo: https://github.com/ditschi/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: protect-files
        # Note: pre-commit appends the filenames of staged files to the command.
        #       To seperate the globs from the list of filenames add a '--'
        args: ['--protected-files-globs', '.gitconfig', '--']
