---
- name: Check az installed
  ansible.builtin.command: az --version
  register: az_cli_installed
  changed_when: false
  failed_when: false

- name: Install Azure CLI (official installer)
  ansible.builtin.shell: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  args:
    executable: /bin/bash
  when: az_cli_installed.rc != 0
