# Tab completion for `machine`, generated by the CLI itself (`machine completion zsh`)
# so it never drifts from the real commands. Cached to avoid starting python on every
# shell; regenerated whenever the installed machine binary is newer than the cache.

(( $+functions[compdef] )) || return
(( $+commands[machine] )) || return

_machine_comp="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/_machine"
if [[ ! -s $_machine_comp || ${commands[machine]:A} -nt $_machine_comp ]]; then
    mkdir -p "${_machine_comp:h}"
    machine completion zsh >|"$_machine_comp" 2>/dev/null
fi
source "$_machine_comp"
unset _machine_comp
